# Generated by Django 5.1.1 on 2024-09-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=50)),
                ('application_data', models.TextField()),
            ],
        ),
    ]
