# Generated by Django 5.1.1 on 2024-12-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0002_callrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecord',
            name='calling_number',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=55),
        ),
    ]
