# Generated by Django 5.1.1 on 2024-12-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0004_alter_client_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecord',
            name='client_image',
            field=models.ImageField(blank=True, null=True, upload_to='call_images/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='client_images/'),
        ),
    ]
